name: Convert Clash Rules
on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 午夜运行
  push:
    branches: [ main ]
  workflow_dispatch: # 支持手动触发

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run conversion script
        run: python convert_all_clash_rules.py
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add converted_rules/*
          git commit -m "Update converted Clash rules" || echo "No changes to commit"
          git push
